name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: "3.10"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          # No Playwright install needed for Selenium

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --maxfail=1 -n auto --junitxml=reports/junit.xml --alluredir=allure-results || true

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: |
            reports/*
            allure-results/*

      - name: Upload coverage (if generated)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Notify Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"CI tests failed for $GITHUB_REPOSITORY on $GITHUB_REF"}' \
          ${{ secrets.SLACK_WEBHOOK }}
